import turtle
turtle.shape("turtle")
turtle.color("black")
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.end_fill()

turtle.right(90)

turtle.color("red")
turtle.begin_fill()
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.end_fill()

turtle.forward(50)

turtle.color("yellow")
turtle.begin_fill()
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.end_fill()
